# Generated by Django 2.2.24 on 2021-10-13 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
